### ISSUE TITLE
Script broken with Blender 2.76b?

### ISSUE THREAD

**Issue by tr37ion** [ucupumar/bevel-curve-tools#1]
I duplicated some mesh edges, converted them to curves (object mode Alt+C) and then tried to use your AddOn. Unfortunately I get this error message with Blender 2.76b:

```
bpy.ops.object.editmode_toggle()
Traceback (most recent call last):
  File "/home/tom/.config/blender/2.76/scripts/addons/bevel-curve-tools-master/__init__.py", line 282, in draw
    if obj.type == 'CURVE':
AttributeError: 'NoneType' object has no attribute 'type'

location: <unknown location>:-1

Traceback (most recent call last):
  File "/home/tom/.config/blender/2.76/scripts/addons/bevel-curve-tools-master/__init__.py", line 282, in draw
    if obj.type == 'CURVE':
AttributeError: 'NoneType' object has no attribute 'type'

location: <unknown location>:-1
```

Btw. can I use the script with several curves selected the same time? Would be nice.

**Comment by ucupumar** [comment]
I have tried to reproduce the bug and got different error. But it's still an error nevertheless. So, I'll still label this as a bug. Anyway, I already knew source of the problem, but it will takes time to fix. Please stay tune.

**Comment by tr37ion** [comment]
No worries, take your time. When you are finished, you may promote your work a bit by writing to Blendernation.

**Comment by ucupumar** [comment]
Lol, 4 years bug, I think this one should be solved by now. I'm closing this issue.
