### ISSUE TITLE
Blender 2.9.

### ISSUE THREAD

**Issue by johngtorres** [ucupumar/bevel-curve-tools#11]
I am missing features such as Radius fall off and shape. Here's a screenshot 
![image](https://user-images.githubusercontent.com/36018162/107865257-7a0ca000-6e32-11eb-8a10-4db3d3852e20.png)

**Comment by Raichuboy17** [comment]
I have the exact same issue and don't know what to do. Yusuf plz help, I love your add-on.

**Comment by ucupumar** [comment]
The menu will appear on the bottom left after you created the beveled curve
![2021-12-04](https://user-images.githubusercontent.com/5253453/144700489-0bc94616-7901-4cf8-824c-9a8d27d4a8e8.png)
I'm closing this issue.
