### ISSUE TITLE
re: bevel curve tools 2.79 release

### ISSUE THREAD

**Issue by meta-androcto** [ucupumar/bevel-curve-tools#2]
hi, iv'e added bevel curve tools into addons release in the add curve extra objects addon. I can do some amazing things with this. Thanks so much :)
Will note you in the release notes.
Brendon. addons team.

**Comment by ucupumar** [comment]
Sorry for late reply, thank you, I'm glad that I can contribute to Blender official release 😄 
I think I'll close this issue when Blender 2.79 comes out 😜

**Comment by ucupumar** [comment]
Now this addon works on both Blender 2.79 and 2.80, feel free to include it on official release or not. Now I'm closing this issue.

**Comment by meta-androcto** [comment]
hello! ok, we can see what we can do. Thanks!
