### ISSUE TITLE
i can't see 'to union mesh' button, blender 2.8

### ISSUE THREAD

**Issue by yuti** [ucupumar/bevel-curve-tools#4]
<img width="1384" alt="wer" src="https://user-images.githubusercontent.com/8939330/61586337-0e0d7b80-abac-11e9-8a9a-79f7d355368f.PNG">
<img width="371" alt="wfew" src="https://user-images.githubusercontent.com/8939330/61586343-27162c80-abac-11e9-9726-1559086b6152.PNG">

i can't see 'to union mesh' button

**Comment by ucupumar** [comment]
Please try to install it again, I think I already fixed the bug
