### ISSUE TITLE
Add support for blender 2.9

### ISSUE THREAD

**Issue by leiserfg** [ucupumar/bevel-curve-tools#7]
The api is the same, just need to change the version check.

**Comment by iredmedia** [comment]
Just tested changing the following and worked like a charm (obviously wrong from a technical standpoint, as is_28 should probably be renamed or have a new check added.)

```
bl_info = {
...
    "blender": (2, 90, 0),
...
}

...
def is_28():
    return bpy.app.version_string.startswith('2.9')
```

**Comment by leiserfg** [comment]
It is better to compare `bpy.app.version` with  `(2, 80)` so both will work.

**Comment by ucupumar** [comment]
Sorry for late response. I already updated the codes to support future version of Blender.
